
version: '2'

volumes:
  peer1-org2:

networks:
  mytest:

services:

  couchdb1:
    container_name: couchdb1
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "5984:5984"
    networks:
      - mytest

  peer1-org2:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
      - couchdb1

  peer1-org2:
    container_name: peer1-org2
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net_mytest
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/tlscacerts/tls-cacert.pem
      - CORE_PEER_ID=peer1-org2
      - CORE_PEER_ADDRESS=peer1-org2:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1-org2:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1-org2:7051
      - CORE_PEER_CHAINCODEADDRESS=peer1-org2:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      #- CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - /app/hlf/mytest-network/organizations/peerOrganizations/Org2/peers/peer1-org2/msp:/etc/hyperledger/fabric/msp
        - /app/hlf/mytest-network/organizations/peerOrganizations/Org2/peers/peer1-org2/tls:/etc/hyperledger/fabric/tls
        - peer1-org2:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
    extra_hosts:
      - "centos81:192.168.56.21"
      - "centos82:192.168.56.22"
      - "centos83:192.168.56.23"
      - "orderer1-org1:192.168.56.21"
      - "peer1-org1:192.168.56.21"
      - "peer1-org2:192.168.56.22"
      - "peer1-org3:192.168.56.23"
    networks:
      - mytest

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      #- CORE_PEER_ID=cli
      #- CORE_PEER_ADDRESS=peer1-org1:7051
      #- CORE_PEER_LOCALMSPID=Org1MSP
      #- CORE_PEER_TLS_ENABLED=true
      #- CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/peer1/tls/tlscacerts/tls-centos81-7055.pem
      #- CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/peer1/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - /app/hlf/mytest-network/organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
    depends_on:
      - peer1-org2
    extra_hosts:
      - "centos81:192.168.56.21"
      - "centos82:192.168.56.22"
      - "centos83:192.168.56.23"
      - "orderer1-org1:192.168.56.21"
      - "peer1-org1:192.168.56.21"
      - "peer1-org2:192.168.56.22"
      - "peer1-org3:192.168.56.23"
    networks:
      - mytest
