version: "3.9"

networks:
  mytest:

volumes:
  pg-data:
  pgadmin-data:

services:
  postgres-org2:
    container_name: postgres-org2
    image: postgres:12
    environment:
      POSTGRES_USER: pg-synergy
      POSTGRES_PASSWORD: pg-synergypw
      POSTGRES_DB: synergy
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - mytest

  pgadmin-org2:
    container_name: pgadmin-org2
    image: dpage/pgadmin4:6
    depends_on:
      - postgres-org2
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - mytest
