NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/hlf-node1-7065.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/hlf-node1-7065.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/hlf-node1-7065.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/hlf-node1-7065.pem
    OrganizationalUnitIdentifier: orderer
