#!/bin/bash

### Dammavalam, Srirangam
### 01-JUN-2021

#[[ "${0}" = "-bash" ]] && { __script_dir__=${PWD}; } || { __script_dir__=$(dirname $0); }
__script_dir__=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
__conf_file__=${__script_dir__}/../network.conf
__helper_utils__=${__script_dir__}/../scripts/helper_utils
if [ ! -f ${__helper_utils__} ]; then echo "${__helper_utils__} file NOT found. Exiting ..."; return; fi
. ${__helper_utils__}
if [ $# -eq 0 ]; then
    if [ ! -f ${__conf_file__} ]; then echo "${__conf_file__} file NOT found. Exiting ..."; return; fi
    . ${__conf_file__}
else
    __vars_file__=$1
    if [ ! -f ${__vars_file__} ]; then echo "${__vars_file__} NOT found. Exiting ..."; return; fi
    . ${__vars_file__}
fi

export COMPOSE_PROJECT_NAME=net
export NETWORK_DIR=${HLF_HOME}/mytest-network
export FABRIC_CFG_PATH=${HLF_HOME}/config/

export CORE_PEER_LOCALMSPID=${ORG_MSPID}
export CORE_PEER_ADDRESS=${HLF_CA_HOST}:${HLF_ORG_PEER1_PORT}
export CORE_PEER_MSPCONFIGPATH=$HLF_NETWORK_DIR/organizations/peerOrganizations/${ORG_NAME}/users/Admin@${ORG_NAME}/msp
export CORE_PEER_TLS_ENABLED=true
export CORE_PEER_TLS_ROOTCERT_FILE=$HLF_NETWORK_DIR/organizations/peerOrganizations/${ORG_NAME}/peers/${HLF_ORG_PEER1_ID}/tls/tlscacerts/tls-cacert.pem
export ORDERER_CA=$HLF_NETWORK_DIR/organizations/ordererOrganizations/${HLF_ORDR_ORG_NAME}/msp/tlscacerts/tls-cacert.pem
export ORDERER_ADDRESS=${HLF_ORDR_HOST}:${HLF_ORDR_PORT}

## IPFS
export IPFS_CLUSTER_SECRET=64d0be1e4a0a2713bda4aa5be8462ae6103eb6ac77e760ce6f9d11b2bb6faff8

